services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../.env
    environment:
      - DOCKER_API_VERSION=1.40
      - WATCHTOWER_SCHEDULE=0 0 8 * * *  # pull updates daily at 8am UTC (2-3am CT)
      - WATCHTOWER_CLEANUP=true        # clean up old images after update
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_EXCLUDE=immich-server,immich-machine-learning,immich-redis,immich-postgres,minecraft,remarkable-bridge,nginx-proxy-manager
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=jf.fagerberg@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=jf.fagerberg@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=jf.fagerberg@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${GMAIL_APP_PASSWORD}
    restart: unless-stopped
