services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3002:3000/tcp"   # web UI (setup wizard)
      - "8853:8853/udp"   # DNS-over-QUIC (optional)
    restart: unless-stopped
