services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=999    # run: id plex
      - PGID=1002 # run: getent group plex-ro
      - TZ=America/Chicago
      - VERSION=docker
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"    # video
      - "993"   # render
    volumes:
      - ./config:/config
      - /mnt/media:/mnt/media
    restart: unless-stopped
