services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Chicago
      - DOMAIN=https://passwords.jasonfagerberg.duckdns.org
      - SIGNUPS_ALLOWED=true   # disable after creating your account
    ports:
      - "8888:80"
    restart: unless-stopped
