services:
  faster-whisper:
    image: fedirz/faster-whisper-server:latest-cuda
    container_name: faster-whisper
    ports:
      - "8005:8000"
    env_file:
      - ../.env
    environment:
      - WHISPER__MODEL=${WHISPER_MODEL:-Systran/faster-whisper-large-v3}
    volumes:
      - ./model-cache:/root/.cache/huggingface
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
