services:
  audiobookshelf:
    image: lscr.io/linuxserver/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - PUID=993
      - PGID=1002
      - TZ=America/Chicago
    volumes:
      - /mnt/plex01/audiobooks:/audiobooks
      - ./config:/config
      - ./metadata:/metadata
    ports:
      - 13378:80
    restart: unless-stopped
