version: 7
daemon:
  log_level: info
  admin_group: sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:7551-1849:5413-0000:23:00.0:
    fan_control_enabled: false
    fan_control_settings:
      mode: curve
      static_speed: 0.9
      temperature_key: edge
      interval_ms: 500
      curve:
        30: 0.2
        60: 0.35
        75: 0.55
        85: 0.75
        95: 1.0
    power_cap: 300.0
    max_memory_clock: 1359
    voltage_offset: -75
  1002:7551-1849:5413-0000:c3:00.0:
    fan_control_enabled: false
    fan_control_settings:
      mode: curve
      static_speed: 0.9
      temperature_key: edge
      interval_ms: 500
      curve:
        30: 0.2
        60: 0.35
        75: 0.55
        85: 0.75
        95: 1.0
    power_cap: 300.0
    max_memory_clock: 1359
    voltage_offset: -75
current_profile: null
auto_switch_profiles: false
